services:
  server:
    build: ./server/
    restart: always
    ports:
      - 5000:5000
    networks:
      - watt-flow-network
    environment:
      SERVER_PORT: 5000
      ENV: ${ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_OUTPUT: ${LOG_OUTPUT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      INFLUX_URL: "http://influxdb2:8086"
      RESTART: ${RESTART}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: "password"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:13
    command: -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - watt-flow-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always

  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASS}
      DOCKER_INFLUXDB_INIT_ORG: watt-flow
      DOCKER_INFLUXDB_INIT_BUCKET: flow
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - watt-flow-network
    healthcheck:
        test: "curl -f http://localhost:8086/ping"
        interval: 5s
        timeout: 10s
        retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status"]
        interval: 5s
        timeout: 20s
        retries: 5
    networks:
      - watt-flow-network

  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/root/redis
        - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_PASSWORD=password
        - REDIS_PORT=6379
      networks:
        - watt-flow-network

  consumer:
    build: ./consumer/
    restart: always
    stop_grace_period: 50s
    ports:
      - "9000:9000"
    networks:
      - watt-flow-network
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres
      DB_TABLE: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
      INFLUX_URI: "http://influxdb2:8086"
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      REDIS_ADDR: "redis:6379"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  bill-worker:
    build: ./bill-worker/
    restart: always
    stop_grace_period: 20s
    networks:
      - watt-flow-network
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      EMAIL_SECRET: "qcwb rfyi hiyi ehxo"
      DB_HOST: postgres
      DB_TABLE: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
      INFLUX_URI: "http://influxdb2:8086"
      INFLUX_TOKEN: ${INFLUX_TOKEN}
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb2:
        condition: service_healthy
      postgres:
        condition: service_healthy

  simulator-1:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "b78f12f3-6e6d-4a18-9dc2-b0b3b2bdea18"
      DEVICE_CITY: "Novi Sad"
      DEVICE_STREET: "Bulevar OsloboÄ‘enja"
      DEVICE_NUMBER: "34"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator1.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started


  simulator-2:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "6f8c4d5a-3d69-46a0-9161-17a0740de53d"
      DEVICE_CITY: "Beograd"
      DEVICE_STREET: "Takovska"
      DEVICE_NUMBER: "34"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator2.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-3:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "a2d55f19-f390-4b3a-9fb8-8459016b4de0"
      DEVICE_CITY: "Kragujevac"
      DEVICE_STREET: "Street"
      DEVICE_NUMBER: "34"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator3.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-4:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "570c2e53-8cd1-4508-b36f-bdf7c8340b09"
      DEVICE_CITY: "Beograd"
      DEVICE_STREET: "Bulevar Kralja Aleksandra"
      DEVICE_NUMBER: "34"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator4.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-5:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "b1e5218a-65ee-4866-9edc-4e0f7f60b2db"
      DEVICE_CITY: "Novi Sad"
      DEVICE_STREET: "Telep"
      DEVICE_NUMBER: "35"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator5.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-6:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "43d827b7-e850-4280-894e-6ea208f5c674"
      DEVICE_CITY: "Beograd"
      DEVICE_STREET: "Vojvode Stepe"
      DEVICE_NUMBER: "38"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator6.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-7:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "f8c58e71-a407-4e90-ab1f-9ecca92545e1"
      DEVICE_CITY: "Kraljevo"
      DEVICE_STREET: "Kralja Petra I"
      DEVICE_NUMBER: "39"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator7.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-8:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "65baf674-3c5e-495a-8237-695ccc22229a"
      DEVICE_CITY: "Kosjeric"
      DEVICE_STREET: "Karadjordjeva"
      DEVICE_NUMBER: "55"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator8.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-9:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "55f55fc9-dd9c-46d4-bab0-b7610b137f0d"
      DEVICE_CITY: "Beograd"
      DEVICE_STREET: "Karadjordjeva"
      DEVICE_NUMBER: "66"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator9.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started

  simulator-10:
    build: ./simulator/
    restart: always
    networks:
      - watt-flow-network
    environment:
      DEVICE_ID: "d0856422-b53e-42fc-9a64-d85efaaee3b0"
      DEVICE_CITY: "Sombor"
      DEVICE_STREET: "Milosa Obilica"
      DEVICE_NUMBER: "544"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - ./config/simulator10.json:/usr/src/app/config/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/profile_pictures:/usr/share/nginx/html/profile_pictures
      - ./data/protected_files:/usr/share/nginx/html/protected_files
      - ./data/ownership_images:/usr/share/nginx/html/ownership_images
      - ./data/ownership_documents:/usr/share/nginx/html/ownership_documents
      - ./data/property_images:/usr/share/nginx/html/property_images
      - ./data/property_documents:/usr/share/nginx/html/property_documents
      - ./front/dist:/usr/share/nginx/html/frontend

    networks:
      - watt-flow-network
    restart: always

volumes:
  postgres-db-volume:
  influxdb2-data:
  influxdb2-config:
  rabbitmq_data:
  redis-data:
networks:
  watt-flow-network:
